title: Morrison Külsenn - Estatística e Probabilidade
description: Portal dedicado ao estudo e aplicação de conceitos estatísticos e probabilísticos. Conteúdo educativo sobre análise de dados, inferência estatística e modelos estatísticos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://morrisonkulsenn.com" # substitua pelo seu domínio real quando estiver em produção

# Build settings
markdown: kramdown
theme: minima # Using a theme for simplicity, can be removed if custom layout is fully built

# Pagination Settings (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 3 # Show 3 posts per page on the blog index
  permalink: 	'/page/:num/' # URL structure for paginated pages
  title: 	':title - Página :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - rouge
  # - jekyll-polyglot
  - jekyll-sitemap

# Configurações de internacionalização (comentadas para uso futuro)
# languages: ["pt", "en"]
# default_lang: "pt"
# exclude_from_localization: ["assets", "images", "css", "js"]
# parallel_localization: false

# Configuração de idioma padrão
lang: "pt"

# Configuração de destaque de sintaxe
highligher: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# A linha 'include: - tag_pages_generated' foi removida daqui.

