title: Morrison Külsenn - Estatística e Probabilidade
description: Portal dedicado ao estudo e aplicação de conceitos estatísticos e probabilísticos.
baseurl: "/morrison-kulsenn"
url: "https://morrisonkulsenn.github.io"

# Build settings
markdown: kramdown
theme: minima

# Pagination Settings
paginate: 3
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - rouge
  - jekyll-sitemap

# Configuração de idioma padrão
lang: "pt"

# Configuração de destaque de sintaxe
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

